name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2.1.1
        with:
          fetch-depth: 2

      - name: Check if there is a parent commit
        id: check-parent-commit
        run: |
          echo "::set-output name=sha::$(git rev-parse --verify --quiet HEAD^)"

      - name: Detect and tag new version
        id: check-version
        if: steps.check-parent-commit.outputs.sha
        uses: salsify/action-detect-and-tag-new-version@v1.0.3
        with:
          version-command: |
            cat VERSION

      - name: Publish package to PyPI
        if: steps.check-version.outputs.tag
        run: |
          echo Published ${{ steps.check-version.outputs.tag }} to PyPI

      - name: Publish package to TestPyPI
        if: "! steps.check-version.outputs.tag"
        run: |
          echo Published ${{ steps.check-version.outputs.tag }} to TestPyPI

      - name: Publish the release notes
        run: |
          echo publish: ${{ steps.check-version.outputs.tag != '' }}
          echo tag: ${{ steps.check-version.outputs.tag }}
